### ISSUE TITLE
No config option to disable extra modifiers?

### ISSUE THREAD

**Issue by blahthebiste** [liketechnik/Liketechnik-s-Tinker-Tweaks#2]
The description for this mod says that you can choose whether to grant extra modifier slots on top of the random modifiers, but the config has no such option, and it seems that by default every level grants modifiers + modifier slots.

**Comment by blahthebiste** [comment]
My bad, did not see the option in the config

**Comment by blahthebiste** [comment]
But, it still gives me extra modifiers (seems like more than 1 per level?) even though this is set to false in the config (the default value).

**Comment by liketechnik** [comment]
I'll try to find some time to look into this on the weekend, but can't promise anything, there's a lot of other stuff to-do for me currently.

Nevertheless, you could help me by answering the following questions:

Which version of Tinker's did/do you use together with this mod? Just to make sure this isn't an issue that was created due to changes in TC that I don't account for.

Did you notice anything in the log by chance?

**Comment by blahthebiste** [comment]
I actually do think the issue may have been due to having Tinkers Tool Leveling also installed when the tool was originally created. I won't ask you to look into this at all until I can reproduce it on my end

**Comment by liketechnik** [comment]
I'm going to close this then. Please re-open it in case the issue occurs again :)
